scan_timeout = 2
add_newline = false

[line_break]
disabled = true

[aws]
disabled = true

[cobol]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[cmake]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[dotnet]
disabled = true

[docker_context]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[golang]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[nodejs]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[ocaml]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[sudo]
disabled = true

[swift]
disabled = true
