require("user.impatient")
require("user.options")
require("user.plugins")

require("user.autocmd")
require("user.autopairs")
require("user.cmp")
require("user.colorizer")
require("user.colorscheme")
require("user.comments")
require("user.gitsigns")
require("user.indentline")
require("user.keymaps")
require("user.nvim-tree")
require("user.lsp")
require("user.lualine")
require("user.telescope")
require("user.treesitter")
